# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa36d258f64295ff3d345c505b57943ccae4aafdb652badbbee744a9b04e7e7cd693e36b4eae19515380d34e5129590c9e2d42c4040655807994e06456cae19

test:
  secret_key_base: 423a6e942fd5632859c186cc087ab0503f009ddaee114e539be6c9861a21b140d73469ea68eac365aa4db33fa377a687c3cd8ac6b8741e9596a416e6082a0f5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
